/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/monk.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";

export function Monk({ loading, props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/monk.glb");

  const { animations: idle } = useFBX("/animations/Idle.fbx");
  idle[0].name = "idle";

  const { animations: phone } = useFBX("/animations/phone.fbx");
  phone[0].name = "phone";

  const { animations: thank } = useFBX("/animations/thank.fbx");
  thank[0].name = "thank";

  const { actions } = useAnimations([idle[0], phone[0], thank[0]], group);

  useEffect(() => {
    if (loading) {
      actions["phone"].reset().play();
    } else {
      actions["idle"].reset().play();
    }

    return () => {
      actions["thank"].reset().stop();
    };
  }, [loading]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[0, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Ch39"
            geometry={nodes.Ch39.geometry}
            material={materials.Ch39_Body}
            skeleton={nodes.Ch39.skeleton}
            castShadow
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/monk.glb");
